name: "ci: "

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

  build:
    name: build
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Next.js Project
        run: bun run build
        env:
          NODE_ENV: production

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Jest Tests
        run: bun run jest
        env:
          NODE_ENV: test

      - name: Run Cypress Tests in Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          install: false
          browser: chrome
          record: false
          build: bun run next build
          start: bun run next start --port 3000
          wait-on: "http://localhost:3000"
