# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install Bun
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Cache Bun Dependencies
        id: bun-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Set up Bun in the environment
      - name: Set up Bun environment
        run: echo "export PATH=\"/home/runner/.bun/bin:\$PATH\"" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: bun add

      # Build the project
      - name: Build
        run: bun run build

      # Run tests
      - name: Run tests
        run: bun run test
