# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'bun' # Change cache to 'bun' for caching Bun dependencies

    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash

    - name: Set up Bun environment
      run: echo "export PATH=\"/home/runner/.bun/bin:\$PATH\"" >> $GITHUB_ENV

    - name: Install dependencies
      run: bun install

    - name: Build
      run: bun run build

    - name: Run tests
      run: bun run test
