name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Jest Tests
        run: bun run jest
        env:
          NODE_ENV: test

      - name: Start Next.js Server
        run: bun run next start --port 3000 &
        env:
          NODE_ENV: test

      - name: Wait for localhost:3000 to be ready
        run: |
          n=0
          until [ $n -ge 30 ]  # Increase this value for more attempts
          do
            curl -s http://localhost:3000 && break
            n=$((n+1))
            sleep 5  # Increase this value to wait longer between attempts
          done

      - name: Cypress Install
        uses: cypress-io/github-action@v5
        with:
          install: false

      - name: Run Cypress Tests
        run: bun run cypress run
        env:
          NODE_ENV: test
